"""详细设计第 7 章逐指令业务用例目录。

每个 case 都有稳定 ID；accept/reject 是 HTTP 业务预期，不是解析器单元测试预期。
模板字段从 instruction-config.json 的 tokens 替换，确保跑道、航路点、程序等
使用当前训练组固定参考快照中的真实数据。
"""

from __future__ import annotations

from typing import Any, Dict, Iterable, List, Mapping, Sequence


def accept(case_id: str, text: str, *, parsed: Mapping[str, Any] | None = None,
           observed: Sequence[str] = ("COMPLETED",), requires: Iterable[str] = (),
           scheduling: str = "REPLACE") -> Dict[str, Any]:
    return {"id": case_id, "kind": "INSTRUCTION", "text": text, "http": [202],
            "parsed": dict(parsed or {}), "observedStatuses": list(observed),
            "requires": list(requires), "scheduling": scheduling, "replay": True}


def structured(case_id: str, command_type: str, parameters: Mapping[str, Any], *,
               observed: Sequence[str] = ("COMPLETED",),
               requires: Iterable[str] = ()) -> Dict[str, Any]:
    return {"id": case_id, "kind": "INSTRUCTION", "command": {
                "type": command_type, "parameters": dict(parameters)},
            "http": [202], "parsed": dict(parameters),
            "observedStatuses": list(observed), "requires": list(requires), "replay": True}


def reject(case_id: str, text: str, *, http: Sequence[int] = (400,),
           code: str | None = "INVALID_INSTRUCTION",
           requires: Iterable[str] = ()) -> Dict[str, Any]:
    return {"id": case_id, "kind": "INSTRUCTION", "text": text,
            "http": list(http), "code": code, "requires": list(requires),
            "assertNoInstructionCreated": True}


CASES: Dict[str, List[Dict[str, Any]]] = {
    "ACID": [
        {"id": "unique-three-char", "kind": "ACID", "suffix": "{acidUnique3}",
         "outcome": "UNIQUE", "requires": ["acidUnique3"]},
        {"id": "unique-four-char", "kind": "ACID", "suffix": "{acidUnique4}",
         "outcome": "UNIQUE", "requires": ["acidUnique4"]},
        {"id": "ambiguous-keeps-selection", "kind": "ACID", "suffix": "{acidAmbiguous3}",
         "outcome": "AMBIGUOUS", "requires": ["acidAmbiguous3"]},
        {"id": "not-found-keeps-selection", "kind": "ACID", "suffix": "ZZZZ",
         "outcome": "NOT_FOUND"},
        {"id": "two-char-rejected", "kind": "ACID", "suffix": "12", "outcome": "INVALID"},
        reject("must-not-enter-instruction-api", "ACID {acidUnique3}"),
    ],
    "HDG": [
        accept("heading-090", "HDG 090", parsed={"magneticHeadingDeg": 90}),
        accept("heading-360-normalized", "HDG 360", parsed={"magneticHeadingDeg": 0}),
        accept("forced-left", "HDG L 090", parsed={"turnDirection": "L", "magneticHeadingDeg": 90}),
        accept("forced-right", "HDG R 270", parsed={"turnDirection": "R", "magneticHeadingDeg": 270}),
        accept("case-and-whitespace", "  hdg   180  ", parsed={"magneticHeadingDeg": 180}),
        reject("above-360", "HDG 361"), reject("missing-value", "HDG"),
        reject("invalid-direction", "HDG X 090"), reject("decimal-heading", "HDG 90.5"),
    ],
    "LEFT": [
        accept("relative-min", "LEFT 1", parsed={"mode": "RELATIVE", "valueDeg": 1, "turnDirection": "L"}),
        accept("relative-max", "LEFT 99", parsed={"mode": "RELATIVE", "valueDeg": 99, "turnDirection": "L"}),
        accept("absolute-three-digit", "LEFT 090", parsed={"mode": "ABSOLUTE", "valueDeg": 90}),
        accept("absolute-360", "LEFT 360", parsed={"mode": "ABSOLUTE", "valueDeg": 0}),
        reject("relative-zero", "LEFT 0"), reject("four-digits", "LEFT 0090"),
        reject("missing", "LEFT"), reject("non-numeric", "LEFT XX"),
    ],
    "RIGHT": [
        accept("relative-min", "RIGHT 1", parsed={"mode": "RELATIVE", "valueDeg": 1, "turnDirection": "R"}),
        accept("relative-max", "RIGHT 99", parsed={"mode": "RELATIVE", "valueDeg": 99, "turnDirection": "R"}),
        accept("absolute-three-digit", "RIGHT 270", parsed={"mode": "ABSOLUTE", "valueDeg": 270}),
        accept("absolute-360", "RIGHT 360", parsed={"mode": "ABSOLUTE", "valueDeg": 0}),
        reject("relative-zero", "RIGHT 0"), reject("absolute-overflow", "RIGHT 361"),
        reject("missing", "RIGHT"), reject("signed", "RIGHT +30"),
    ],
    "ALT": [
        accept("feet", "ALT 30000FT", parsed={"altitudeFtMsl": 30000}),
        accept("flight-level", "ALT FL200", parsed={"altitudeFtMsl": 20000}),
        accept("meters", "ALT 9000M", parsed={"altitudeFtMsl": {"approx": 29527.559, "tolerance": 1}}),
        accept("embedded-vs", "ALT 30000FT VS 1000FPM",
               parsed={"altitudeFtMsl": 30000, "verticalRateFpm": 1000}),
        accept("vendor-lvl", "LVL FL180", parsed={"altitudeFtMsl": 18000,
                                                   "normalizedText": "ALT FL180"}),
        reject("over-envelope", "ALT 70000FT", http=(422,), code="PERFORMANCE_LIMIT_EXCEEDED"),
        reject("invalid-decimal-separator", "ALT 9000,5M"),
        reject("embedded-vs-over-envelope", "ALT 30000FT VS 7000FPM", http=(422,),
               code="PERFORMANCE_LIMIT_EXCEEDED"),
        reject("missing", "ALT"),
    ],
    "VS": [
        accept("climb-fpm", "VS +1000FPM", parsed={"verticalRateFpm": 1000}),
        accept("descent-mps", "VS -5MPS",
               parsed={"verticalRateFpm": {"approx": -984.252, "tolerance": 1}}),
        accept("zero", "VS 0", parsed={"verticalRateFpm": 0}),
        accept("vendor-cr", "CR 1200", parsed={"verticalRateFpm": 1200,
                                                "normalizedText": "VS +1200"}),
        accept("vendor-dr", "DR 800", parsed={"verticalRateFpm": -800,
                                               "normalizedText": "VS -800"}),
        reject("unsigned-nonzero", "VS 1000"),
        reject("above-envelope", "VS +6001FPM", http=(422,), code="PERFORMANCE_LIMIT_EXCEEDED"),
        reject("comma-decimal", "VS +5,5MPS"), reject("missing", "VS"),
    ],
    "SPD": [
        accept("knots", "SPD 280KT", parsed={"indicatedAirspeedKt": 280}),
        accept("kmh", "SPD 500KMH",
               parsed={"indicatedAirspeedKt": {"approx": 269.978, "tolerance": 0.1}}),
        accept("plain-terminal-unit", "SPD 250", parsed={"indicatedAirspeedKt": 250}),
        accept("vendor-speed", "SPEED 260KT", parsed={"indicatedAirspeedKt": 260,
                                                       "normalizedText": "SPD 260KT"}),
        reject("above-envelope", "SPD 601KT", http=(422,), code="PERFORMANCE_LIMIT_EXCEEDED"),
        reject("mach-not-guessed", "SPD M0.78"), reject("comma-decimal", "SPD 280,5KT"),
    ],
    "MACH": [
        accept("nominal", "MACH 0.78", parsed={"mach": 0.78}),
        # 解析包线边界（0.1/0.99）受理为 202，但超出运输类性能包线：
        # 收敛判据物理不可达，业务预期为预算耗尽 FAILED（详细设计 6.3.4）
        accept("lower-bound", "MACH 0.1", parsed={"mach": 0.1},
               observed=("FAILED",)),
        accept("upper-bound", "MACH 0.99", parsed={"mach": 0.99},
               observed=("FAILED",)),
        reject("below-envelope", "MACH 0.09", http=(422,), code="PERFORMANCE_LIMIT_EXCEEDED"),
        reject("above-envelope", "MACH 1.0", http=(422,), code="PERFORMANCE_LIMIT_EXCEEDED"),
        reject("comma-decimal", "MACH 0,78"),
    ],
    "DCT": [
        accept("point-in-route", "DCT {routePoint}", parsed={"targetPoint": "{routePoint}",
                                                              "captureExitAnchor": True},
               requires=("routePoint",)),
        accept("temporary-point", "DCT {offRoutePoint}", parsed={"targetPoint": "{offRoutePoint}",
                                                                  "captureExitAnchor": True},
               requires=("offRoutePoint",)),
        reject("missing", "DCT"), reject("invalid-point", "DCT BAD_POINT"),
        reject("unknown-reference", "DCT {unknownPoint}", http=(422,), code="REFERENCE_NOT_FOUND",
               requires=("unknownPoint",)),
    ],
    "RTE": [
        accept("atomic-full-route", "RTE {routeText}", parsed={"replacementMode": "FULL_UNFLOWN"},
               requires=("routeText",)),
        reject("destination-not-last", "RTE {routePoint} {offRoutePoint}",
               requires=("routePoint", "offRoutePoint")),
        reject("unknown-point-atomic-rollback", "RTE {unknownPoint} {destination}",
               http=(422,), code="REFERENCE_NOT_FOUND", requires=("unknownPoint", "destination")),
        reject("missing-route", "RTE"), reject("invalid-token", "RTE BAD_POINT {destination}",
                                                requires=("destination",)),
    ],
    "RESUME": [
        accept("auto", "RESUME", parsed={"mode": "AUTO", "resumePoint": None}),
        accept("explicit", "RESUME {routePoint}", parsed={"mode": "EXPLICIT",
                                                           "resumePoint": "{routePoint}"},
               requires=("routePoint",)),
        reject("flown-point", "RESUME {flownPoint}", http=(400,), code="INVALID_INSTRUCTION",
               requires=("flownPoint",)),
        reject("too-many-args", "RESUME A B"),
    ],
    "ORBIT": [
        accept("current-left-default-radius", "ORBIT L",
               parsed={"action": "ENTER", "turnDirection": "L", "radiusNm": 5},
               observed=("EXECUTING",)),
        accept("current-right-min-radius", "ORBIT R 1NM",
               parsed={"action": "ENTER", "radiusNm": 1}, observed=("EXECUTING",)),
        accept("center-max-radius", "ORBIT {routePoint} L 20NM",
               parsed={"action": "ENTER", "centerPoint": "{routePoint}", "radiusNm": 20},
               observed=("EXECUTING",), requires=("routePoint",)),
        accept("vendor-hold-left", "HOLD L", parsed={"action": "ENTER", "turnDirection": "L",
                                                     "normalizedText": "ORBIT L"},
               observed=("EXECUTING",)),
        accept("exit", "ORBIT EXIT", parsed={"action": "EXIT"}),
        reject("missing-direction", "ORBIT"), reject("below-radius", "ORBIT L 0NM"),
        reject("above-radius", "ORBIT R 21NM"), reject("invalid-direction", "ORBIT X 5NM"),
    ],
    "HOLD": [
        accept("fix-right-seconds", "HOLD {holdFix} R 090 60",
               parsed={"action": "FIX_AND_LEG", "legSeconds": 60},
               observed=("EXECUTING",), requires=("holdFix",)),
        accept("fix-left-minutes", "HOLD {holdFix} L 270 2MIN",
               parsed={"action": "FIX_AND_LEG", "legSeconds": 120},
               observed=("EXECUTING",), requires=("holdFix",)),
        accept("fix-distance-boundary", "HOLD {holdFix} R 090 20NM",
               parsed={"action": "FIX_AND_LEG", "legNm": 20},
               observed=("EXECUTING",), requires=("holdFix",)),
        accept("published", "HOLD {holdProcedure}", parsed={"action": "PUBLISHED_PROCEDURE",
                                                             "procedureName": "{holdProcedure}"},
               observed=("EXECUTING",), requires=("holdProcedure",)),
        accept("exit", "HOLD EXIT", parsed={"action": "EXIT"}),
        reject("seconds-below", "HOLD {holdFix} R 090 29", requires=("holdFix",)),
        reject("seconds-above", "HOLD {holdFix} R 090 181", requires=("holdFix",)),
        reject("distance-below", "HOLD {holdFix} R 090 1NM", requires=("holdFix",)),
        reject("invalid-direction", "HOLD {holdFix} X 090 60", requires=("holdFix",)),
    ],
    "OFFSET": [
        accept("left-min", "OFFSET L 1NM", parsed={"action": "APPLY", "side": "L", "distanceNm": 1}),
        accept("right-max", "OFFSET R 10NM", parsed={"action": "APPLY", "side": "R", "distanceNm": 10}),
        accept("clear", "OFFSET CLR", parsed={"action": "CLEAR"}),
        accept("empty-alias-clear", "OFFSET", parsed={"action": "CLEAR", "normalizedText": "OFFSET CLR"}),
        accept("compact-right", "OFFSET R5", parsed={"side": "R", "distanceNm": 5,
                                                      "normalizedText": "OFFSET R 5NM"}),
        accept("standalone-compact-right", "R5", parsed={"side": "R", "distanceNm": 5,
                                                          "normalizedText": "OFFSET R 5NM"}),
        accept("standalone-compact-left", "L5", parsed={"side": "L", "distanceNm": 5,
                                                        "normalizedText": "OFFSET L 5NM"}),
        accept("bare-number-right", "OFFSET 5", parsed={"side": "R", "distanceNm": 5,
                                                         "normalizedText": "OFFSET R 5NM"}),
        reject("below", "OFFSET L 0NM"), reject("above", "OFFSET R 11NM"),
        reject("invalid-side", "OFFSET X 5NM"),
    ],
    "VOR": [
        accept("inbound", "VOR {vor} IN 090", parsed={"station": "{vor}", "direction": "IN",
                                                       "radialDeg": 90}, requires=("vor",)),
        accept("outbound", "VOR {vor} OUT 270", parsed={"station": "{vor}", "direction": "OUT",
                                                         "radialDeg": 270}, requires=("vor",)),
        accept("dme-arc", "VOR {vorDme} IN 180 DME 12NM",
               parsed={"station": "{vorDme}", "dmeDistanceNm": 12}, requires=("vorDme",)),
        accept("vendor-t-inbound", "VOR 090T {vor}",
               parsed={"station": "{vor}", "direction": "IN", "radialDeg": 90},
               requires=("vor",)),
        accept("vendor-f-outbound", "VOR 270F {vor}",
               parsed={"station": "{vor}", "direction": "OUT", "radialDeg": 270},
               requires=("vor",)),
        reject("ordinary-waypoint-t-alias", "VOR {ordinaryPoint} IN 090", http=(422,),
               code="REFERENCE_NOT_FOUND", requires=("ordinaryPoint",)),
        reject("invalid-direction", "VOR {vor} SIDE 090", requires=("vor",)),
        reject("radial-overflow", "VOR {vor} IN 361", requires=("vor",)),
        reject("dme-overflow", "VOR {vorDme} IN 090 DME 51NM", requires=("vorDme",)),
    ],
    "SIDSTAR": [
        accept("procedure", "SIDSTAR {procedure}", parsed={"procedureId": "{procedure}"},
               requires=("procedure",)),
        accept("with-report-point", "SIDSTAR {procedure} {reportPoint}",
               parsed={"procedureId": "{procedure}", "reportPoint": "{reportPoint}"},
               requires=("procedure", "reportPoint")),
        reject("unknown-procedure", "SIDSTAR {unknownProcedure}", http=(422,),
               code="REFERENCE_NOT_FOUND", requires=("unknownProcedure",)),
        reject("missing", "SIDSTAR"), reject("too-many", "SIDSTAR PROC A B"),
    ],
    "P_LEVEL": [
        accept("feet", "P_LEVEL {futureLeg} 12000FT", parsed={"legPoint": "{futureLeg}",
                                                               "altitudeFtMsl": 12000},
               requires=("futureLeg",)),
        accept("flight-level", "P_LEVEL {futureLeg} FL200", parsed={"altitudeFtMsl": 20000},
               requires=("futureLeg",)),
        reject("flown-leg", "P_LEVEL {flownPoint} 12000FT", requires=("flownPoint",)),
        reject("over-envelope", "P_LEVEL {futureLeg} 70000FT", http=(422,),
               code="PERFORMANCE_LIMIT_EXCEEDED", requires=("futureLeg",)),
        reject("missing-height", "P_LEVEL {futureLeg}", requires=("futureLeg",)),
    ],
    "P_TIME": [
        accept("relative", "P_TIME {futureLeg} T+600", parsed={"legPoint": "{futureLeg}",
                                                                "format": "RELATIVE"},
               requires=("futureLeg",)),
        accept("absolute-day", "P_TIME {futureLeg} {futureAbsoluteTime}",
               parsed={"format": "ABSOLUTE_DAY"}, requires=("futureLeg", "futureAbsoluteTime")),
        accept("same-day-hhmm", "P_TIME {futureLeg} {futureHhmm}",
               parsed={"format": "HHMM_SAME_DAY"}, requires=("futureLeg", "futureHhmm")),
        reject("past-hhmm-no-rollover", "P_TIME {futureLeg} {pastHhmm}",
               requires=("futureLeg", "pastHhmm")),
        reject("invalid-clock", "P_TIME {futureLeg} 2460", requires=("futureLeg",)),
        reject("flown-leg", "P_TIME {flownPoint} T+600", requires=("flownPoint",)),
    ],
    "TAKEOFF": [
        accept("immediate", "TAKEOFF {departureRunway} LEVEL 5000FT",
               parsed={"runway": "{departureRunway}", "targetAltitudeFtMsl": 5000},
               requires=("departureRunway", "preDepartureAircraft")),
        accept("scheduled-relative", "TAKEOFF {departureRunway} AT T+60 LEVEL 5000FT",
               parsed={"scheduledTimeFormat": "RELATIVE"},
               observed=("BLOCKED", "DISPATCHING", "EXECUTING", "COMPLETED"),
               requires=("departureRunway", "preDepartureAircraft")),
        reject("wrong-phase", "TAKEOFF {departureRunway} LEVEL 5000FT", http=(409,),
               code="PROCEDURE_STATE_INVALID", requires=("departureRunway", "airborneAircraft")),
        reject("unknown-runway", "TAKEOFF {unknownRunway} LEVEL 5000FT", http=(422,),
               code="REFERENCE_NOT_FOUND", requires=("unknownRunway",)),
        reject("past-time", "TAKEOFF {departureRunway} AT {pastHhmm} LEVEL 5000FT",
               requires=("departureRunway", "pastHhmm")),
        reject("missing-level", "TAKEOFF {departureRunway}", requires=("departureRunway",)),
    ],
    "ILS": [
        accept("full", "ILS {destination} {arrivalRunway} L 020",
               parsed={"airportCode": "{destination}", "runway": "{arrivalRunway}",
                       "turnDirection": "L", "interceptMagneticHeadingDeg": 20},
               observed=("EXECUTING", "COMPLETED"),
               requires=("destination", "arrivalRunway", "approachAircraft")),
        accept("default-airport", "ILS {arrivalRunway} R 340",
               parsed={"airportCode": "{destination}", "runway": "{arrivalRunway}"},
               observed=("EXECUTING", "COMPLETED"),
               requires=("destination", "arrivalRunway", "approachAircraft")),
        reject("unknown-runway", "ILS {destination} {unknownRunway} L 020", http=(422,),
               code="REFERENCE_NOT_FOUND", requires=("destination", "unknownRunway")),
        reject("invalid-turn", "ILS {destination} {arrivalRunway} X 020",
               requires=("destination", "arrivalRunway")),
        reject("heading-overflow", "ILS {destination} {arrivalRunway} L 361",
               requires=("destination", "arrivalRunway")),
        reject("hard-envelope", "ILS {destination} {arrivalRunway} L 020", http=(422,),
               code="PERFORMANCE_LIMIT_EXCEEDED", requires=("destination", "arrivalRunway",
                                                              "outsideIlsEnvelopeAircraft")),
    ],
    "MISSED": [
        accept("auto-procedure", "MISSED", parsed={"execution": "P13"},
               requires=("approachAircraft",)),
        accept("named-procedure", "MISSED {missedProcedure}",
               parsed={"missedProcedureId": "{missedProcedure}"},
               requires=("approachAircraft", "missedProcedure")),
        reject("wrong-phase", "MISSED", http=(409,), code="PROCEDURE_STATE_INVALID",
               requires=("airborneAircraft",)),
        reject("unknown-procedure", "MISSED {unknownProcedure}", http=(422,),
               code="REFERENCE_NOT_FOUND", requires=("unknownProcedure",)),
    ],
    "SQK": [
        accept("leading-zero", "SQK 0042", parsed={"action": "SET", "squawk": "0042"}),
        accept("upper-bound", "SQK 7777", parsed={"squawk": "7777"}),
        accept("clear", "SQK CLR", parsed={"action": "CLEAR", "squawk": None}),
        accept("vendor-alias", "SSRCODE 0123", parsed={"squawk": "0123",
                                                       "normalizedText": "SQK 0123"}),
        reject("zero-rejected", "SQK 0000"), reject("contains-eight", "SQK 0048"),
        reject("three-digits", "SQK 042"), reject("five-digits", "SQK 00042"),
    ],
    "SSRMODE": [
        accept("mode-a", "SSRMODE A", parsed={"ssrMode": "A"}),
        accept("mode-c", "SSRMODE C", parsed={"ssrMode": "C"}),
        reject("invalid-mode", "SSRMODE S"), reject("missing", "SSRMODE"),
    ],
    "NML": [
        accept("restore-planned", "NML", parsed={"action": "RESTORE_PLANNED"}),
        reject("extra-argument", "NML NOW"),
        {"id": "atomic-invalid-planned-values", "kind": "INSTRUCTION", "text": "NML",
         "http": [400, 422], "code": None, "requires": ["invalidPlannedTransponderAircraft"],
         "assertNoBusinessSideEffect": ["squawk", "ssrMode"]},
    ],
    "IDENT": [
        accept("activate", "IDENT", parsed={"transponderIdentActive": True,
                                             "durationSeconds": 18}),
        accept("repeat-restarts-timer", "IDENT", parsed={"restartsOnRepeat": True}),
        reject("extra-argument", "IDENT NOW"),
        reject("id-is-not-ident", "ID", http=(422,), code="FEATURE_PROFILE_NOT_CONFIGURED"),
    ],
    "NSPEED": [
        accept("restore-managed", "NSPEED", parsed={"action": "RESTORE_MANAGED"}),
        reject("extra-argument", "NSPEED NOW"),
        reject("must-not-bypass-hard-envelope", "NSPEED", http=(409, 422), code=None,
               requires=("speedProtectionAircraft",)),
    ],
    "ID": [
        {"id": "missing-profile", "kind": "STRUCTURED", "command": {"type": "ID",
             "parameters": {}}, "http": [422], "code": "FEATURE_PROFILE_NOT_CONFIGURED",
         "requires": ["profileAbsentAircraft"], "assertNoInstructionCreated": True},
        structured("published-profile", "ID", {}, observed=("COMPLETED",),
                   requires=("idProfileConfigured",)),
        reject("text-id-is-not-ident", "ID", http=(422,), code="FEATURE_PROFILE_NOT_CONFIGURED"),
        {"id": "checksum-not-loaded", "kind": "STRUCTURED", "command": {"type": "ID",
             "parameters": {}}, "http": [503], "code": "PROFILE_NOT_LOADED",
         "requires": ["profileChecksumMismatchAircraft"], "assertNoInstructionCreated": True},
    ],
    "DECOMP": [
        {"id": "missing-profile-n", "kind": "STRUCTURED", "command": {"type": "DECOMP",
             "parameters": {"modeCode": "N"}}, "http": [422],
         "code": "FEATURE_PROFILE_NOT_CONFIGURED", "requires": ["profileAbsentAircraft"],
         "assertNoInstructionCreated": True},
        structured("mode-n", "DECOMP", {"modeCode": "N"}, requires=("decompProfilesConfigured",)),
        structured("mode-s", "DECOMP", {"modeCode": "S"}, requires=("decompProfilesConfigured",)),
        structured("clear", "DECOMP", {"modeCode": "CLR"}, requires=("decompProfilesConfigured",)),
        {"id": "invalid-mode", "kind": "STRUCTURED", "command": {"type": "DECOMP",
             "parameters": {"modeCode": "X"}}, "http": [400], "code": "INVALID_INSTRUCTION",
         "assertNoInstructionCreated": True},
    ],
    "FRE": [
        reject("must-not-enter-instruction-api", "FRE {targetFrequency}"),
        {"id": "missing-revision", "kind": "FRE_MISSING_REVISION",
         "targetFrequency": "{targetFrequency}", "http": [428],
         "code": "REVISION_REQUIRED", "requires": ["targetFrequency"]},
        {"id": "stale-revision", "kind": "FRE_STALE_REVISION",
         "targetFrequency": "{targetFrequency}", "http": [409],
         "code": "REVISION_CONFLICT", "requires": ["targetFrequency"]},
        {"id": "missing-idempotency-key", "kind": "FRE_MISSING_IDEMPOTENCY",
         "targetFrequency": "{targetFrequency}", "http": [400],
         "code": "IDEMPOTENCY_KEY_REQUIRED", "requires": ["targetFrequency"]},
        {"id": "unknown-frequency", "kind": "FRE", "targetFrequency": "{unknownFrequency}",
         "http": [404], "code": "TERMINAL_NOT_FOUND", "requires": ["unknownFrequency"]},
        {"id": "non-owner-rejected", "kind": "FRE_FOREIGN", "targetFrequency": "{targetFrequency}",
         "http": [403], "code": "AIRCRAFT_NOT_ASSIGNED", "requires": ["foreignTerminal"]},
        {"id": "direct-handover", "kind": "FRE", "targetFrequency": "{targetFrequency}",
         "http": [200], "replay": True, "requires": ["targetFrequency", "targetTerminal"]},
    ],
    "DEL": [
        reject("must-not-enter-instruction-api", "DEL"),
        {"id": "preview-summary-and-token", "kind": "DEL_PREVIEW", "http": [200],
         "requires": ["deletableAircraft"]},
        {"id": "delete-requires-token", "kind": "DEL_WITHOUT_TOKEN", "http": [428],
         "code": "CONFIRMATION_REQUIRED", "requires": ["deletableAircraft"]},
        {"id": "foreign-token-rejected", "kind": "DEL_FOREIGN_TOKEN", "http": [428],
         "code": "CONFIRMATION_REQUIRED", "requires": ["foreignTerminal", "deletableAircraft"]},
        {"id": "tampered-token-rejected", "kind": "DEL_TAMPERED_TOKEN", "http": [428],
         "code": "CONFIRMATION_REQUIRED", "requires": ["deletableAircraft"]},
        {"id": "token-bound-to-aircraft", "kind": "DEL_OTHER_AIRCRAFT_TOKEN", "http": [428],
         "code": "CONFIRMATION_REQUIRED",
         "requires": ["deletableAircraft", "secondaryAircraftId"]},
        {"id": "revision-change-invalidates-token", "kind": "DEL_REVISION_CHANGED_TOKEN",
         "http": [428], "code": "CONFIRMATION_REQUIRED",
         "requires": ["revisionChangedTokenAircraft"]},
        {"id": "thirty-second-expiry", "kind": "DEL_EXPIRED_TOKEN", "http": [428],
         "code": "CONFIRMATION_REQUIRED", "requires": ["expiredTokenAircraft"]},
        {"id": "delete-requires-idempotency-key", "kind": "DEL_MISSING_IDEMPOTENCY",
         "http": [400], "code": "IDEMPOTENCY_KEY_REQUIRED",
         "requires": ["missingIdempotencyAircraft"]},
        {"id": "confirm-once-and-replay-rejected", "kind": "DEL_CONFIRM", "http": [202],
         "requires": ["deletableAircraft"]},
    ],
}


def command_types() -> List[str]:
    return list(CASES)
